FROM node:24.1-alpine
WORKDIR /back

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

ENV GOOGLE_APPLICATION_CREDENTIALS=firebase-service-account.json

EXPOSE 3000
CMD [ "npm" , "run", "start" ]