name: CI - Back

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    env: 
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/back/firebase-service-account.json
      FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.6.0'

      - name: Install dependencies
        run: |
          cd back
          npm install

      - name: Create firebase-service-account.json
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > back/firebase-service-account.json

      - name: Build the server
        run: npm run build
        working-directory: back

      - name: Check formatting
        run: npm run format:check
        working-directory: back

      - name: Run tests
        run: npm run test
        working-directory: back