name: CD - Back

on:
  workflow_run:
    workflows: ["CI - Back"]
    branches: [main, cd]
    types:
      - completed

jobs:
  deploy-back:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - uses: docker/build-push-action@v5
        with:
          context: ./back
          file: ./back/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}-back:latest
