name: Publish Frontend Docker Image

on:
  workflow_run:
    workflows: ["CI - Front"]
    types:
      - completed

jobs:
  publish-front:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./front
          push: true
          tags: ghcr.io/${{ github.repository }}-front:latest
