name: CI - Front

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'


jobs:
  test-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.6.0'

      - name: Install dependencies
        run: |
          cd front
          npm install

      - name: Run build
        run: npm run build
        working-directory: front

      - name: Check code format with Prettier
        run: npm run format:check
        working-directory: front

      - name: Start Docker
        run: docker-compose up -d

      - name: Run cypress tests
        run: npx cypress run
        working-directory: front