name: CI - Front

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'


jobs:
  test-frontend:
    runs-on: ubuntu-latest

    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/back/firebase-service-account.json
      FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      CYPRESS_EMAIL: ${{ secrets.CYPRESS_EMAIL }}
      CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.6.0'

      - name: Install dependencies
        run: |
          cd back
          npm install

      - name: Create firebase-service-account.json
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > back/firebase-service-account.json

      - name: Build the server
        run: npm run build
        working-directory: back

      - name: Run back
        run: npm run start &
        working-directory: back

      - name: Install dependencies
        run: |
          cd front
          npm install

      - name: Run build
        run: npm run build
        working-directory: front

      - name: Run front
        run: npm run dev &
        working-directory: front

      - name: Check code format with Prettier
        run: npm run format:check
        working-directory: front

      - name: Run cypress tests
        run: npx cypress run
        working-directory: front