name: CI - Front

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'


jobs:
  test-frontend:
    runs-on: ubuntu-latest

    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/back/firebase-service-account.json
      FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      CYPRESS_EMAIL: ${{ secrets.CYPRESS_EMAIL }}
      CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.6.0'

      - name: Install dependencies
        run: |
          cd back
          npm install

      - name: Create firebase-service-account.json
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > back/firebase-service-account.json

      - name: Build backend
        run: npm run build
        working-directory: back

      - name: Start backend in background
        run: npm run start > ../back.log 2>&1 &
        working-directory: back

      - name: Wait for backend
        run: npx wait-on http://localhost:3000

      - name: Install frontend dependencies
        run: npm install
        working-directory: front

      - name: Build frontend
        run: npm run build
        working-directory: front

      - name: Start frontend in background
        run: npm run dev > ../front.log 2>&1 &
        working-directory: front

      - name: Wait for frontend
        run: npx wait-on http://localhost:5173

      - name: Check code format with Prettier
        run: npm run format:check
        working-directory: front

      - name: Run Cypress tests
        run: npx cypress run
        working-directory: front

      - name: Output backend & frontend logs on failure
        if: failure()
        run: |
          echo "========= BACKEND LOG ========="
          cat back.log || echo "No backend log found"

          echo "========= FRONTEND LOG ========="
          cat front.log || echo "No frontend log found"