name: Auto Tagging

permissions:
  contents: write

on:
  push:
    branches:
      - Ci-Cd-upgraded
 #     - main
  #    - dev

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          latest_tag=$(git tag -l | sort -V | tail -n 1)
          if [ -z "$latest_tag" ]; then
            latest_tag="0.0.0"
          fi
          echo "Latest tag: $latest_tag"
          echo "tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Calculate next version
        id: bump
        run: |
          branch="${GITHUB_REF##*/}"
          version="${{ steps.get_tag.outputs.tag }}"
          version="${version#v}"

          IFS='.' read -r major minor patch <<< "$version"

          if [ "$branch" = "main" ]; then
            major=$((major + 1))
            minor=0
            patch=0
          elif [ "$branch" = "Ci-Cd-upgraded" ]; then
            minor=$((minor + 1))
            patch=0
          fi

          new_tag="$major.$minor.$patch"
          echo "New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Create Git tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.bump.outputs.new_tag }}
          git push origin ${{ steps.bump.outputs.new_tag }}